import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import importPlugin from 'eslint-plugin-import';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/generated/**',
      '**/coverage/**',
      '**/*.config.js',
      '**/*.config.mjs',
      '**/*.config.cjs',
      // Generated by Next on every build.
      '**/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    plugins: { import: importPlugin },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-floating-promises': 'off',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='Date'][arguments.length=0]",
          message:
            'Use clock.now() from @orbit/core instead of new Date() so time is injectable in tests.',
        },
      ],
    },
  },

  // ── Architectural boundaries (BUILD-PLAN.md §5 working agreements) ───────────
  {
    files: ['apps/web/**/*.{ts,tsx}', 'packages/core/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'bullmq',
              importNames: ['Worker'],
              message:
                'The web app must never consume queue jobs (DECISION D-002). Workers live in apps/worker only.',
            },
            {
              // The producer half of @orbit/queue is fine here; the consumer
              // half is not. `assertWorkerProcess` also refuses at runtime, but
              // failing at lint is a shorter feedback loop than failing at boot.
              name: '@orbit/queue',
              importNames: ['startWorker', 'blockingConnection', 'installShutdownHandlers'],
              message:
                'The web app may only enqueue. Job processing belongs to apps/worker (DECISION D-002, D-020).',
            },
            {
              name: '@prisma/client',
              message:
                'Import the tenant-scoped client from @orbit/db instead — a raw PrismaClient bypasses tenant isolation (DECISION D-005).',
            },
          ],
          patterns: [
            {
              group: ['@orbit/providers/*/'],
              message:
                'Import from @orbit/providers only. Provider-specific code must not leak outside its adapter (SRS §8).',
            },
          ],
        },
      ],
    },
  },

  // Provider adapters are the one place platform-specific code belongs.
  {
    files: ['packages/providers/**/*.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },

  // apps/web and packages/ui are compiled by a bundler (moduleResolution:
  // Bundler), which does not rewrite a `.js` specifier back to the `.ts` source
  // the way NodeNext-built packages require. Typecheck passes either way, so
  // without this rule the mistake only surfaces at `next build`.
  {
    files: ['apps/web/**/*.{ts,tsx}', 'packages/ui/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            'ImportDeclaration[source.value=/^\\.\\.?\\/.*\\.js$/], ExportNamedDeclaration[source.value=/^\\.\\.?\\/.*\\.js$/]',
          message:
            'Bundler-resolved code must use extensionless relative imports. Drop the .js — it resolves at typecheck but fails at build.',
        },
        {
          selector: "NewExpression[callee.name='Date'][arguments.length=0]",
          message:
            'Use clock.now() from @orbit/core instead of new Date() so time is injectable in tests.',
        },
      ],
    },
  },

  // The db package is the only place a raw PrismaClient may be constructed.
  {
    files: ['packages/db/**/*.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },

  {
    files: ['**/*.test.ts', '**/*.test.tsx', '**/test/**/*.ts', 'packages/db/prisma/seed.ts'],
    rules: {
      'no-console': 'off',
      'no-restricted-syntax': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  prettier,
);
