import type { MetricAvailability, Platform, SocialAccountStatus } from '@orbit/core';
import type { PlatformCapabilities } from './capabilities.js';
import type { ValidationResult, VariantDraft } from './validation.js';

/**
 * The provider contract (SRS §8, docs/ARCHITECTURE.md §6).
 *
 * The core publishing engine knows only this interface. It never learns a
 * platform's name, endpoints, field names, or quirks — those live entirely
 * inside an adapter, and anything the core needs to *decide* is expressed as
 * data in `PlatformCapabilities`.
 *
 * Two deliberate departures from the SRS §8 sketch, which §8 permits:
 *   • `reconcile()` — without it, exactly-once publishing is unachievable
 *     against a provider that offers no idempotency key.
 *   • `validate()` is pure and synchronous, separated from `publish()`, so the
 *     same code runs in the composer and on the server.
 */

// ── Credentials ─────────────────────────────────────────────────────────────

/**
 * A decrypted credential, in memory, inside the provider layer only.
 *
 * Never logged, never serialised into an API response, never returned to the
 * frontend (SRS §6). The redaction layer strips these field names by default.
 */
export interface DecryptedCredential {
  accessToken: string;
  refreshToken?: string | undefined;
  /** Absent when the provider issues non-expiring credentials. */
  expiresAt?: Date | undefined;
  /** Latest moment a refresh could still succeed. */
  refreshableUntil?: Date | undefined;
  scopes: readonly string[];
  /** Which encryption key version sealed this, so keys can rotate. */
  keyVersion: number;
}

/** What a provider hands back after obtaining or refreshing a credential. */
export interface IssuedCredential {
  accessToken: string;
  refreshToken?: string | undefined;
  expiresAt?: Date | undefined;
  refreshableUntil?: Date | undefined;
  scopes: readonly string[];
}

export type RefreshOutcome =
  | { status: 'REFRESHED'; credential: IssuedCredential }
  /** Still valid and not near expiry; nothing to do. */
  | { status: 'STILL_VALID' }
  /** Cannot be refreshed — the account must be reconnected by a human. */
  | { status: 'REQUIRES_RECONNECT'; reason: string };

// ── OAuth ───────────────────────────────────────────────────────────────────

export interface AuthorizationUrlInput {
  /** Where the provider should send the user back to. */
  redirectUri: string;
  /** Signed, single-use, session-bound. Generated by the caller (SRS §6). */
  state: string;
  /** Additional scopes beyond the provider's default set. */
  extraScopes?: readonly string[] | undefined;
  /**
   * Which login surface to use, for a platform that has more than one.
   *
   * Instagram is the only such platform: the same account can be reached
   * through the Facebook Page it is linked to, or through Instagram's own
   * login. They are different OAuth hosts with different scopes, and the choice
   * has to be made *before* any account exists — so it cannot be read off one.
   *
   * Providers with a single surface ignore it.
   */
  accountType?: string | undefined;
}

export interface CallbackInput {
  code: string;
  redirectUri: string;
  /** The surface the authorization was started on. See `AuthorizationUrlInput`. */
  accountType?: string | undefined;
}

/**
 * One connectable account discovered during OAuth.
 *
 * A single authorization commonly yields several (a Meta user administering
 * many Pages), so the connect flow is always "exchange, then choose".
 */
export interface DiscoveredAccount {
  externalId: string;
  displayName: string;
  handle?: string | undefined;
  avatarUrl?: string | undefined;
  accountType?: string | undefined;
  /** Per-account credential, where the provider issues one (Meta Page tokens). */
  credential: IssuedCredential;
}

export interface ConnectedAccounts {
  /** Credential for the authorizing user, when distinct from per-account ones. */
  userCredential?: IssuedCredential | undefined;
  accounts: readonly DiscoveredAccount[];
}

// ── Health ──────────────────────────────────────────────────────────────────

export interface AccountHealth {
  status: SocialAccountStatus;
  /** Scopes the provider says we currently hold. */
  grantedScopes: readonly string[];
  /** Scopes required for publishing that are missing. */
  missingScopes: readonly string[];
  /** Safe, human-readable explanation when not ACTIVE. */
  message?: string | undefined;
  checkedAt: Date;
}

// ── Publishing ──────────────────────────────────────────────────────────────

/** A media item resolved to something the provider can fetch or stream. */
export interface PublishMedia {
  id: string;
  kind: 'IMAGE' | 'VIDEO' | 'GIF';
  mimeType: string;
  sizeBytes: number;
  /** Short-lived signed URL the provider may fetch from. */
  url: string;
  altText?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  durationMs?: number | undefined;
  frameRate?: number | undefined;
  /** Highest instantaneous rate — what a platform's own checker objects to. */
  peakFrameRate?: number | undefined;
}

export interface PublishContext {
  credential: DecryptedCredential;
  account: { externalId: string; accountType?: string | undefined };
  draft: VariantDraft;
  media: readonly PublishMedia[];
  /**
   * Stable fingerprint of the content, used as an idempotency key where the
   * provider accepts one and as the reconciliation marker where it does not.
   */
  contentHash: string;
  /** Threaded into provider request headers where supported, for tracing. */
  correlationId: string;
  /** Abort signal so a hung provider call cannot pin a worker slot. */
  signal?: AbortSignal | undefined;
  /**
   * Persist an opaque handle *before* making a call whose outcome could be
   * ambiguous, so reconciliation can later ask the platform a direct question
   * instead of inferring the answer from a listing.
   *
   * The shape is the provider's own business — the engine stores it and hands
   * it back verbatim in `ReconcileContext.providerRef`, and no code outside the
   * adapter that wrote it may interpret it. Awaiting the call is the point: a
   * handle written after the ambiguous request would not exist in the case it
   * was written for.
   */
  recordProviderRef?: ((ref: Record<string, unknown>) => Promise<void>) | undefined;
  /**
   * Whatever this adapter recorded on an **earlier attempt**, verbatim.
   *
   * Exists so a retry can resume rather than start over. Platforms that build a
   * container and then transcode it — Threads, Instagram Reels — can take
   * minutes on a long video, which is longer than any sane per-call budget. If
   * a retry always created a *new* container the transcode would restart every
   * time and a slow video could never publish at all: each attempt would run out
   * of budget at exactly the same point.
   *
   * An adapter that finds a usable handle here picks up where it left off. One
   * that does not recognise the shape ignores it and starts fresh, which is
   * always safe — an unpublished container is invisible and expires on its own.
   */
  previousRef?: Record<string, unknown> | undefined;
}

export interface PublishResult {
  externalPostId: string;
  permalink?: string | undefined;
  publishedAt: Date;
  /** Whitelisted, non-sensitive provider fields worth keeping (SRS §14). */
  providerMeta?: Record<string, string | number | boolean> | undefined;
}

export interface ReconcileContext {
  credential: DecryptedCredential;
  account: { externalId: string; accountType?: string | undefined };
  contentHash: string;
  /** Body we attempted, for platforms where matching must fall back to text. */
  body: string;
  /**
   * Whatever the adapter stored through `recordProviderRef` on the attempt
   * being reconciled, verbatim, or undefined if it never wrote one.
   */
  providerRef?: Record<string, unknown> | undefined;
  /** Window to search, bracketing the ambiguous attempt. */
  attemptedAt: Date;
  windowMs: number;
  correlationId: string;
  signal?: AbortSignal | undefined;
}

/**
 * The answer to "did the post we are unsure about actually go out?".
 *
 * `INCONCLUSIVE` is a first-class outcome: the publishing engine parks the
 * variant for a human rather than guessing (docs/ARCHITECTURE.md §5.2).
 */
export type ReconcileResult =
  | { outcome: 'FOUND'; externalPostId: string; permalink?: string | undefined; publishedAt: Date }
  | { outcome: 'NOT_FOUND' }
  | { outcome: 'INCONCLUSIVE'; reason: string };

export interface ExternalPostRef {
  externalPostId: string;
  accountExternalId: string;
}

export interface ExternalPostStatus {
  exists: boolean;
  permalink?: string | undefined;
  publishedAt?: Date | undefined;
  /** Whether this app created it, which gates editing on some platforms. */
  createdByThisApp?: boolean | undefined;
}

// ── Analytics ───────────────────────────────────────────────────────────────

export interface DateRange {
  from: Date;
  to: Date;
}

/**
 * Metrics plus a per-metric availability map.
 *
 * A metric the provider has withdrawn is reported `DEPRECATED`, never stored as
 * zero — SRS §18 requires unavailable metrics be clearly indicated rather than
 * fabricated.
 */
export interface MetricSet {
  metrics: Record<string, number>;
  availability: Record<string, MetricAvailability>;
  capturedAt: Date;
  apiVersion: string;
}

// ── Webhooks ────────────────────────────────────────────────────────────────

export interface RawWebhookRequest {
  headers: Record<string, string | undefined>;
  /** Raw body. Signature verification must run against bytes, not parsed JSON. */
  rawBody: string;
  query?: Record<string, string | undefined> | undefined;
}

export interface ProviderEvent {
  /** Provider-side event id, for webhook idempotency. */
  externalEventId: string;
  type: string;
  accountExternalId?: string | undefined;
  externalPostId?: string | undefined;
  occurredAt: Date;
  payload: Record<string, unknown>;
}

// ── The interface ───────────────────────────────────────────────────────────

/**
 * Methods every provider must implement. A platform that cannot do something
 * declares it in its capabilities; the engine checks the descriptor before
 * calling, so an adapter never has to fake a feature.
 */
export interface SocialProvider {
  readonly platform: Platform;

  /** Descriptor for an account type. Must be cheap — called on every validate. */
  capabilities(accountType?: string | null): PlatformCapabilities;

  // OAuth and credential lifecycle
  getAuthorizationUrl(input: AuthorizationUrlInput): { url: string; scopes: readonly string[] };
  exchangeCode(input: CallbackInput): Promise<ConnectedAccounts>;
  refreshCredential(credential: DecryptedCredential): Promise<RefreshOutcome>;
  probeHealth(
    credential: DecryptedCredential,
    account: { externalId: string },
  ): Promise<AccountHealth>;
  revoke(credential: DecryptedCredential, account: { externalId: string }): Promise<void>;

  // Publishing
  validate(draft: VariantDraft, accountType?: string | null): ValidationResult;
  publish(ctx: PublishContext): Promise<PublishResult>;
  reconcile(ctx: ReconcileContext): Promise<ReconcileResult>;
  getPostStatus(ref: ExternalPostRef, credential: DecryptedCredential): Promise<ExternalPostStatus>;
  deletePost(ref: ExternalPostRef, credential: DecryptedCredential): Promise<void>;

  // Analytics — gated by capabilities.analytics
  fetchPostAnalytics(
    ref: ExternalPostRef,
    credential: DecryptedCredential,
    range: DateRange,
  ): Promise<MetricSet>;
  fetchAccountAnalytics(
    account: { externalId: string },
    credential: DecryptedCredential,
    range: DateRange,
  ): Promise<MetricSet>;

  // Webhooks — gated by capabilities.webhooks.supported
  verifyWebhook?(request: RawWebhookRequest): boolean;
  parseWebhook?(request: RawWebhookRequest): ProviderEvent[];
}
